### ISSUE TITLE
Feature Request: Include tags in CSV export of people

### ISSUE THREAD

**Issue by wonderificdave** [asalant/freehub#23]
In Reports > People > Search > Export all

Include all tags in a new column in the CSV

Why?  For generating a list of current staff with more details about who has keys, what skillset, etc.

**Comment by scottmarinoff** [comment]
Second that emotion! Tags are helpful for keeping track of other important details not captured in distinct fields. 

We store staff contact info in the Freehub db and, when exporting the 'People' list (and filtering by 'staff' status), it would be helpful to see the tags associated with each person's record.

**Comment by asalant** [comment]
Makes sense to me. One thing tricky about exporting tags is that there is that the list of tags is arbitrarily long. One options is to have a single column in the results that has all the tags as a single value separated by commas. The other is to have a series of columns (e.g. named Tag 1, Tag 2, Tag 3,...) with the tags for a person listed out there.

The second option makes the tag data more usable in reports but is still a bit tricky to work with. For the use case you describe (understanding staff skill set) it sounds like the first option would work fine. Thoughts?

Either of you have Ruby on Rails chops you want to apply to this? I'd be happy to review a pull request that adds tags to the Person report.

**Comment by wonderificdave** [comment]
I vote for option 1.  It seems simpler and easier.

I am interested in taking a look at this, but I haven't done Rails in a
very long time.
-dave

**Comment by wonderificdave** [comment]
Implemented
