### ISSUE TITLE
Feature Request: Filter People Report by "staff" field

### ISSUE THREAD

**Issue by wonderificdave** [asalant/freehub#24]
In Reports > People Report

Add filter criteria for staff 
options: blank(all) or true or false
default: blank(all)

This would make it easier to generate current staff list

**Comment by asalant** [comment]
Thanks for the suggestion! I don't have strong feelings about this one as you can download a CSV and easily filter there. 

How often are you looking to generate a current staff list?

**Comment by wonderificdave** [comment]
I agree, it's not a big deal.  Right now I'm exporting a lot as we try and
clean our list up.  Long term I would guess like 4 times a year or so.  I
thought I would throw it out there to see if anyone felt it useful beyond
me.  Maybe if I'm bored one day I will work on it.

**Comment by wonderificdave** [comment]
I would add that it would makes the web report more useful for maintaining the staff list.  You can get the list of staff directly in the system and edit people by clicking through.  What I'm doing now is downloading the csv, filtering by staff, then searching for people in freehub and editing there.  Again, not a big deal though

**Comment by wonderificdave** [comment]
Hi Alon,

I sent you 3 pull requests for the last 3 issues on freehub.  I'm very
rusty with Ruby and especially Rails.  I tested on my local and the changes
worked though!

Thanks,
Dave

**Comment by asalant** [comment]
This is awesome. I'm on vacation until March 21 so will need to check it
out closer when I am back.

Good work getting set up to test locally. We're on pretty old versions of
lots of dependencies and there has not yet been a good motivator to update.

**Comment by wonderificdave** [comment]
Hi Alon,

Have you had a chance to take a look at these?  Also, are there any updates
you would like me to work on or test out?

Thanks!
-dave

**Comment by asalant** [comment]
Hey Dave,

Thanks for the nudge! I will look at your work this weekend.

**Comment by wonderificdave** [comment]
Implemented
